name: savebite-be
services:
  postgres:
    container_name: savebite-db
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - savebite-private
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: savebite-be
    env_file:
      - .env
    image: savebite-be:latest
    restart: always
    depends_on:
      - postgres
    environment:
      - APP_ENV=production
      - APP_PORT=${APP_PORT}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=savebite_user
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES=${JWT_EXPIRES}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - savebite-private

networks:
  savebite-private:
    driver: bridge

volumes:
  postgres: